config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    authenticated :user do
      root to: 'posts#index', as: :authenticated_root
      
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  post '/friendship/create/:id', to: 'friendships#create'

  resources :users, :only => [:show, :index]
  resources :friendships

  resources :posts, :only => [:create, :destroy, :index] do
    resources :likes, module: :posts
    resources :comments, :only => [:create, :destroy] do
      resources :likes, module: :comments
    end
  end


end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: 'author', dependent: :destroy
    has_many :comments, foreign_key: 'user_id'
    has_many :comment_id, through: :comment, source: 'Post'
    has_many :likes, foreign_key: 'user_id'
    has_many :friendships
    has_many :confirmed_friends, -> { where(friendships: { friendship_status: true }) }, through: :friendships, source: :friend
    has_many :inverse_friendships, class_name: 'Friendship', foreign_key: 'friend_id'
    has_many :inverse_confirmed_friends, -> { where(friendships: { friendship_status: true }) }, through: :inverse_friendships, source: :user

    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :validatable,
           :omniauthable, omniauth_providers: %i[facebook]

    def friends_and_own_posts
      Post.where(user: (confirmed_friends + inverse_confirmed_friends + [self]))
    end

    validates :name, presence: true
    validates :lastname, presence: true

    def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.email = auth.info.email
        user.password = Devise.friendly_token[0, 20]
        user.name = auth.info.name.split(' ')[0]
        user.lastname = auth.info.name.split(' ')[1] # assuming the user model has a name
        user.image_link = auth.info.image # assuming the user model has an image
      end
    end

    def self.new_with_session(params, session)
      super.tap do |user|
        if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
          user.email = data['email'] if user.email.blank?
        end
      end
    end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page])
    @post = @user.posts.build
    @comments = Comment.all
  end

  def index
    @users = User.all
    @friendships = current_user.friendships
    @inverse_friendships = current_user.inverse_friendships
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(current_user)
      gravatar_id = Digest::MD5.hexdigest(current_user.email.downcase)
      gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
      image_tag(gravatar_url, alt: current_user.name, class: 'gravatar')
    end

    def its_me?(user)
      user == current_user
    end

    # Users who have yet to confirme friend
    def pending_for_accept_my_request(user)
      friendship1 = @friendships.map { |friendship| friendship.friend if !friendship.friendship_status }.compact
      friendship1.include?(user)
    end

    def pending_for_me_to_accept(user)
      friendship_2 = @inverse_friendships.map { |friendship| friendship.user if !friendship.friendship_status }.compact
      friendship_2.include?(user)
    end

    def we_are_friends(user)
      friends_list = @friendships.map { |friendship| friendship.friend if friendship.friendship_status }
      friends_list += @inverse_friendships.map { |friendship| friendship.user if friendship.friendship_status }
      friends_list.compact
      friends_list.include?(user)
    end

    def finding_friendship_id(user)
      Friendship.find_by(user_id: current_user.id, friend_id: user.id) ||
        Friendship.find_by(user_id: user.id, friend_id: current_user.id)
    end

    def list_pending_friends(user)
      friendship_2 = @inverse_friendships.map { |friendship| friendship.user if !friendship.friendship_status }.compact
      friendship_2
    end
  end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<ul class="text-center">
  <% @users.each do |user| %>
    <li class= "users-list">
    <div>
      <p> <%=gravatar_for(user) %></p>
      <p><%= link_to user.name, user %> <%=link_to user.lastname, user%></p>
      <% if its_me?(user) %>
        <%= button_to 'Go to My Profile ', user, method: :get %>
      <% elsif pending_for_accept_my_request(user) %>
        <%= button_to 'Cancel Request Sent', friendship_path(finding_friendship_id(user)), method: :delete %>
      <% elsif pending_for_me_to_accept(user) %>
        <div>
          <%= button_to 'Accept Request',edit_friendship_path(finding_friendship_id(user)), method: :get %>
          <%= button_to 'Cancel Request',friendship_path(finding_friendship_id(user)), method: :delete %>
        </div>
      <% elsif we_are_friends(user)  %>
        <%= button_to 'Go to My Friend\'s Profile ', user, method: :get %>
        <%= button_to 'Remove',friendship_path(finding_friendship_id(user)), method: :delete %>
      <% elsif %>
        <%= button_to 'Add Friend', "#{authenticated_root_path}friendship/create/#{user.id}", method: :post %>
      <% end %>

      </li>
    </div>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class= "container-fluid">

  <div class= "row">

    <div class= "col-md-4 col-sm-12 user-info text-center">
      <%= gravatar_for(@user)%>
      <p> <%= @user.name %> <%= @user.lastname %> </p>
      <p><%= @user.email %> </p>
    </div>

    <div class="col-md-8 post-info text-center">

    <%= render 'shared/newpost' %>


      <h3>Posts (<%= @user.posts.count %>)</h3>
      <ul class="posts">
        <%= render @posts %>
      </ul>
      <%= will_paginate @posts %>

    </div>
  </div>
</div>