config/routes.rb
Rails.application.routes.draw do

  devise_scope :user do
    authenticated :user do
      root to: 'posts#index', as: :authenticated_root
      
    end

    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  post '/friendship/create/:id', to: 'friendships#create'

  resources :users, :only => [:show, :index]
  resources :friendships

  resources :posts, :only => [:create, :destroy, :index] do
    resources :likes, module: :posts
    resources :comments, :only => [:create, :destroy] do
      resources :likes, module: :comments
    end
  end


end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :find_friendship, only: [:destroy, :edit]

  def new
    @friendships = Friendship.new
  end

  def create
    user = User.find(params[:id])
    @friendship = Friendship.create(user_id: current_user.id, friend_id: user.id, friendship_status: false)
    if @friendship.save
      flash[:success] = 'Friendship request successfull'
      redirect_to users_path
    else
      flash[:danger] = 'Cannot send friendship request'
      redirect_to users_path
    end
  end

  def edit
    if @friendship_id
      @friendship_id.update_attribute(:friendship_status, true)
      flash[:success] = 'Friendship request accepted'
      redirect_to users_path
    else
      flash[:danger] = 'Friendship request not accepted'
      redirect_to users_path
    end
  end

  def destroy
    if @friendship_id
      @friendship_id.destroy
      flash[:success] = 'Friendship request canceled'
      redirect_to users_path
    else
      flash[:danger] = 'Friendship request NOT canceled'
    end
  end

  private

  def find_friendship
    @friendship_id = Friendship.find(params[:id])
  end
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/views/friendships/_form.html.erb
<%= form_with(model: friendship, local: true) do |form| %>
  <% if friendship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friendship.errors.count, "error") %> prohibited this friendship from being saved:</h2>

      <ul>
        <% friendship.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/friendships/edit.html.erb
<h1>Editing Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Show', @friendship %> |
<%= link_to 'Back', friendships_path %>

app/views/friendships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Friendships</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friendships.each do |friendship| %>
      <tr>
        <td><%= link_to 'Show', friendship %></td>
        <td><%= link_to 'Edit', edit_friendship_path(friendship) %></td>
        <td><%= link_to 'Destroy', friendship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friendship', new_friendship_path %>

app/views/friendships/new.html.erb
<h1>New Friendship</h1>

<%= render 'form', friendship: @friendship %>

<%= link_to 'Back', friendships_path %>

app/views/friendships/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_friendship_path(@friendship) %> |
<%= link_to 'Back', friendships_path %>